= OAuth 2.0 Protocols and Patterns

== Warning

The samples in this repo are intended for educational purposes to demonstrate certain
features of spring security and OAuth2 / OpenIdConnect. DO NOT blindly copy and
paste code from this sample app into production applications, the goal of this
sample is not to demonstrate security best practices and make recommendations on how
to secure your system. Please work with your information security team to
determine the suitability of using the patterns shown in the sample to you specific
situation.

== Run the Sample

* Build the sample -> `./gradlew clean build`
* Run UAA Server -> `./gradlew -b uaa-server/build.gradle uaa`
* Run UI App -> `./gradlew -b ui-app/build.gradle bootRun`
* Run Microservice A -> `./gradlew -b microservice-a/build.gradle bootRun`
* Run Microservice B -> `./gradlew -b microservice-b/build.gradle bootRun`
* Run Microservice C -> `./gradlew -b microservice-c/build.gradle bootRun`
* Go to `http://localhost:8080` and login to UAA using *user1/password*

